### ISSUE TITLE
Could not find theme. Ensure this component is wrapped in a ThemeProvider

### ISSUE THREAD

**Issue by avevlad** [ricokahler/hacker-ui#62]
```
npm install --save hacker-ui@next react-style-system
```

Code:

```js
import * as React from 'react';
import { Button, createTheme } from "hacker-ui";
import { ThemeProvider } from 'react-style-system';

const theme = createTheme({});

export default () => {
    return (
        <div>
            <ThemeProvider theme={theme}>
                <Button>Button</Button>
            </ThemeProvider>,
        </div>
    );
};

```

![image](https://user-images.githubusercontent.com/2889662/77236125-ae4cf180-6bcc-11ea-9e04-378aa928390d.png)

**Comment by tompeace** [comment]
```
import { ThemeProvider, createTheme } from 'hacker-ui'
const theme = createTheme()

const App = () => (
    <ThemeProvider theme={theme}>
           ...
    </ThemeProvider>
)
```

This worked for me, but it was not mentioned in the docs, I had to dig around in the examples.

**Comment by pearlzhuzeng** [comment]
Hey @avevlad, try using the ThemeProvider from 'hacker-ui' instead of 'react-style-system':
```
import { ThemeProvider } from 'hacker-ui'
```

**Comment by ricokahler** [comment]
@avevlad My apologizes for the incorrect docs. Follow the advice from @tompeace and @pearlzhuzeng and import the theme provider from `hacker-ui` instead of `react-style-system` and it should work.

I flipped the switch on the docs new docs a bit pre-maturely because the docs of next version of hacker-ui (i.e. `v0.2.0`) has much better performance and is mobile friendly.

However, `v0.2.0` is still unreleased and I haven't audit the docs 😅. I'll update them today along with some patches.

Thanks a bunch for pointing this out!

**Comment by ricokahler** [comment]
@avevlad I updated the documentation. Please feel free to open any similar issues!
